<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerURQ0Qmk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerURQ0Qmk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerURQ0Qmk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerURQ0Qmk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerURQ0Qmk\App_KernelDevDebugContainer([
    'container.build_hash' => 'URQ0Qmk',
    'container.build_id' => '35dc7191',
    'container.build_time' => 1605864963,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerURQ0Qmk');
